# Основные настройки плагина
settings:
  # Стоимость создания нового клана в монетах
  create-cost: 100
  # Максимальная сумма, которую можно вывести из казны за один раз (0 = без лимита)
  max-withdraw: 0
  # Формат сообщений в клановом чате
  clan-chat-format: "&6[Клан] &f%player%&7 - %message%"
  # Минимальное количество символов в названии клана
  clan-name-min: 3
  # Максимальное количество символов в названии клана
  clan-name-max: 16
  # Максимальное количество участников в клане
  max-members: 6

# Настройки сообщений
messages:
  # Префикс для всех сообщений
  prefix: ""
  # Сообщения об ошибках
  error:
    # Используется, когда игрок пытается выполнить команду, требующую членства в клане, но не состоит в нем
    not-in-clan: "&#C50000[❌] &fВы &#C50000не состоите &fв клане!"
    # Используется, когда игрок пытается создать клан с уже занятым названием
    clan-exists: "&#C50000[❌] &fКлан с названием &#DD770D%clan% &fуже существует!"
    # Используется, когда игрок пытается создать клан, но уже состоит в другом
    player-already-in-clan: "&#C50000[❌] &fВы уже состоите в клане!"
    # Используется, когда указанный клан не существует
    clan-not-found: "&#C50000[❌] &fКлан &#DD770D%clan% &fне существует!"
    # Используется, когда игрок пытается выполнить действие, доступное только лидеру клана
    not-leader: "&#C50000[❌] &fТолько &#D6DD0Dлидер &fклана может выполнять это!"
    # Используется, когда указанный игрок не найден на сервере
    player-not-found: "&#C50000[❌] &fИгрок &#DD770D%player% &fне найден!"
    # Используется, когда игрок пытается принять приглашение, которого нет
    no-invitation: "&#C50000[❌] &fУ вас &#C50000нет &fприглашения в клан &#DD770D%clan%&f!"
    # Используется, когда лидер пытается пригласить игрока, который уже в клане
    target-already-in-clan: "&#C50000[❌] &fИгрок уже состоит в клане!"
    # Используется, когда лидер пытается покинуть клан
    cannot-leave-as-leader: "&#C50000[❌] &fЛидер &#C50000не может &fпокинуть клан! Используйте &#DD770D/clan delete&f."
    # Используется, когда у игрока недостаточно монет для действия (например, создание клана или вложение)
    not-enough-money: "&#C50000[❌] &fУ вас &#C50000недостаточно &fмонет! Требуется &#DD770D%amount% &fмонет."
    # Используется, когда игрок пытается исключить игрока, который не в его клане
    player-not-in-clan: "&#C50000[❌] &fИгрок &#DD770D%player% &#DB4444не состоит &fв вашем клане!"
    # Используется, когда в казне клана недостаточно монет для вывода
    not-enough-clan-money: "&#C50000[❌] &fВ казне клана &#C50000недостаточно &fмонет!"
    # Используется, когда указана некорректная сумма (отрицательная или не число)
    invalid-amount: "&#C50000[❌] &fУкажите &#DD770Dкорректную &fсумму"
    # Используется, когда команда /vclans использована неправильно
    usage-message: "&#4498DB[★] &fИспользование: &#4498DB/vclans [reload | point]"
    # Используется, когда у игрока нет прав на выполнение команды (например, /vclans reload)
    no-permission-message: "&#C50000[❌] &fУ вас &#C50000нет прав &fна выполнение этой команды!"
    # Используется, когда сумма вывода превышает лимит (max-withdraw)
    withdraw-limit-exceeded: "&#C50000[❌] &fСумма &6превышает &fлимит снятия! Максимум: &#DD770D%limit% &fмонет."
    # Используется, когда игрок пытается отправить пустое сообщение в клановый чат
    chat-empty-message: "&#C50000[❌] &fУкажите сообщение для &#DD770Dотправки &fв клановый чат!"
    # Используется, когда игрок пытается выгнать самого себя
    cannot-kick-self: "&#C50000[❌] &fВы &#C50000не можете &fвыгнать самого себя!"
    # Используется, когда игрока исключают из клана
    kicked-from-clan: "&#C50000[❌] &fВы были &#C50000исключены &fиз клана &#DD770D%clan%!"
    # Используется, когда игрок пытается создать клан с запрещенными словами
    clan-name-blocked: "&#C50000[❌] &fНазвание клана &#DD770D%clan% &fсодержит &#C50000запрещенное &fслово!"
    # Используется, для /clan top
    invalid-usage-top: "&#4498DB[★] &fИспользование: &#4498DB/clan top [money | kills]"
    # Используется, если у игрока недостаточно монет для покупки чего то в магазине
    shop-not-enough-money: "&#C50000[❌] &fУ вас &#C50000недостаточно &#DD770Dмонет &fдля покупки! Нужно: &#DD770D%amount%"
    # Используется, если у игрока недостаточно поинтов для покупки чего то в магазине
    shop-not-enough-points: "&#C50000[❌] &fУ вас &#C50000недостаточно &#DD770Dпоинтов &fдля покупки! Нужно: &#DD770D%amount%"
    # Используется, если игрок попытаеться создать клан у которого в названии будет меньше символов чем указано в конфиге
    invalid-clan-name-length: "&#C50000[❌] &fНазвание клана должно содержать от &#06C500%min% &fдо &#C50000%max% &fсимволов"

    clan-full: "В клане уже %min_player%/%max_player% участников!"
    clan-full-invite: "Клан %clan% достиг максимального количества участников!"

  # Сообщения об успехе
  success:
    # Используется при успешном создании клана
    clan-created: "&#06C500[✔] &fКлан &#DD770D%clan% &fуспешно создан!"
    # Используется когда лидер успешно приглашает игрока
    player-invited: "&#06C500[✔] &fИгрок &#DD770D%player% &fприглашен в клан!"
    # Используется когда игрок принимает приглашение и вступает в клан
    clan-joined: "&#06C500[✔] &fВы вступили в клан &#DD770D%clan%&f!"
    # Используется при успешном удалении клана
    clan-deleted: "&#06C500[✔] &fКлан &#DD770D%clan% &fуспешно удален!"
    # Используется когда игрок покидает клан
    clan-left: "&#06C500[✔] &fВы покинули клан &#DD770D%clan%&f!"
    # Используется когда лидер исключает игрока из клана
    player-kicked: "&#06C500[✔] &fИгрок &#DD770D%player% &fисключен из клана!"
    # Используется когда PvP между участниками клана включено
    pvp-enabled: "&#06C500[✔] &fPvP между участниками клана &#06C500включено&f!"
    # Используется когда PvP между участниками клана выключено
    pvp-disabled: "&#06C500[✔] &fPvP между участниками клана &#DB4444выключено&f!"
    # Используется когда игрок успешно вносит монеты в казну
    invest-success: "&#06C500[✔] &fВы внесли &#DD770D%amount% &fмонет в казну клана!"
    # Используется когда игрок успешно выводит монеты из казны
    withdraw-success: "&#06C500[✔] &fВы вывели &#DD770D%amount% &fмонет из казны клана!"
    # Используется при просмотре баланса казны
    balance: "&#06C500[✔] &fБаланс казны клана: &#DD770D%balance% &fмонет!"
    # Используется при успешной перезагрузке плагина
    reload-success-message: "&#06C500[✔] &fКонфигурация &#06C500успешно &fперезагружена"
    # Используется для оповещения всех участников клана о внесении монет
    invest-broadcast: "&#06C500[✔] &fИгрок &#DD770D%player% &fвнес &#D0FC5C%amount% &fмонет в казну клана"
    # Используется для оповещения всех участников клана о выводе монет
    withdraw-broadcast: "&#06C500[✔] &fИгрок &#DD770D%player% &fвывел &#D0FC5C%amount% &fмонет из казны клана"
    # Используется когда игрок присоединяется к клану (сообщение для других участников)
    player-joined: "&#06C500[✔] &fИгрок &#DD770D%player% &#06C500присоединился &fк клану!"
    # Используется когда свечение клана включено
    glow-enabled: "&#06C500[✔] &fСвечение клана &#06C500включено&f!"
    # Используется когда свечение клана выключено
    glow-disabled: "&#06C500[✔] &fСвечение клана &#C50000выключено&f!"
    # Используется когда изменен цвет свечения
    glow-color-changed: "&#06C500[✔] &fЦвет свечения соклановцев &#06C500изменен&f!"
    # Используется когда игрок что то покупает в магазине клана
    shop-purchase-success: "&#06C500[✔] &fВы &#06C500успешно &fкупили предмет: %item%!"

    # Сообщения для поинтов
  points:
    error:
      # Используется, когда команда /vclans points использована неправильно
      points-usage: "&#4498DB[★] &fИспользование: &#4498DB/vclans points [give | set | reset] [ник] [кол.]"
      # Используется, когда указана некорректная сумма (отрицательная или не число)
      invalid-amount: "&#C50000[⚠] &fУкажите &#DD770Dкорректное &fколичество поинтов"
      # Используется, когда указанный игрок не найден
      player-not-found: "&#C50000[⚠] &fИгрок &#DD770D%player% &fне найден!"
    success:
      # Используется, когда поинты успешно выданы
      points-given: "&#06C500[✔] &fВы выдали &#0DDD0F%amount% &fпоинтов игроку &#DD770D%player%&f!"
      # Используется, когда игрок получает поинты
      points-received: "&#06C500[✔] &aВам выдали %amount% поинтов!"
      # Используется, когда поинты успешно установлены
      points-set: "&#06C500[✔] &fВы установили &#0DDD0F%amount% &fпоинтов для игрока &#DD770D%player%&f!"
      # Используется, когда поинты успешно сброшены
      points-reset: "&#06C500[✔] &fПоинты игрока &#0DDD0F%player% &#C50000сброшены&f!"

  # Список команд для игроков, не состоящих в клане (для /clan create)
  create-help:
    - ""
    - "&#1BC905[☄] &fПомощь по команде:"
    - " &#1BC905/clan create [назв.] &7- &fСоздать клан"
    - " &#1BC905/clan top money / kills &7- &fПосмотреть топы кланов"

  # Список всех доступных команд для игроков в клане (для /clan)
  clan-help:
    - ""
    - "&#1BC905[☄] &fДоступные команды клана:"
    - " &#1BC905/clan delete &7- &fУдалить клан"
    - " &#1BC905/clan leave &7- &fПокинуть клан"
    - " &#1BC905/clan invite [ник] &7- &fПригласить игрока"
    - " &#1BC905/clan kick [ник] &7- &fИсключить игрока"
    - " &#1BC905/clan pvp &7- &fПереключить урон между участниками"
    - " &#1BC905/clan invest [сумма] &7- &fВложить монеты в казну"
    - " &#1BC905/clan withdraw [сумма] &7- &fВывести монеты из казны"
    - " &#1BC905/clan balance &7- &fУзнать баланс казны"
    - " &#1BC905/clan info &7- &fПосмотреть информацию о клане"
    - " &#1BC905/clan chat [сообщение] &7- &fОтправить сообщение в клан чат"
    - " &#1BC905/clan glow &7- &fПереключить подсветку союзников"
    - " &#1BC905/clan top money/kills &7- &fПосмотреть топы кланов"
    - " &#1BC905/clan menu &7- &fОткрыть меню клана"

  # Сообщение, отправляемое игроку при приглашении в клан
  clan-invite:
    - ""
    - "&fВас пригласили в клан &6%clan%&7!"
    - " &#1BC905/clan accept %clan% &7- &fЧто-бы принять приглашение"

  # Информация о клане, отображаемая при /clan info
  clan-info:
    - ""
    - "&fИнформация о клане &6%clan%:"
    - ""
    - " &7- &fСоздатель: &#E4D53A%leader%"
    - " &7- &fУчастники: &#7CE1CA%members_count% &fигроков"
    - " &7- &fСписок участников: &#7CABE1[%members%]"
    - " &7- &fУбийства: &#EF5252%kills%"
    - " &7- &fМонеты: &#64EF52%balance%"

  # Топ 10 кланов по монетам
  clan-top-money:
    - ""
    - "&#3DC500Т&#41C700о&#45C900п &#4ECD00к&#52CF00л&#56D100а&#5AD300н&#5FD500о&#63D700в &#6BDA00п&#6FDC00о &#78E000б&#7CE200а&#80E400л&#84E600а&#88E800н&#8DEA00с&#91EC00у&#95EE00:"
    - ""
    - "&#34AA001. &f%clan_name_1% &7- &#9AB128%value_1%"
    - "&#34AA002. &f%clan_name_2% &7- &#9AB128%value_2%"
    - "&#34AA003. &f%clan_name_3% &7- &#9AB128%value_3%"
    - "&#34AA004. &f%clan_name_4% &7- &#9AB128%value_4%"
    - "&#34AA005. &f%clan_name_5% &7- &#9AB128%value_5%"
    - "&#34AA006. &f%clan_name_6% &7- &#9AB128%value_6%"
    - "&#34AA007. &f%clan_name_7% &7- &#9AB128%value_7%"
    - "&#34AA008. &f%clan_name_8% &7- &#9AB128%value_8%"
    - "&#34AA009. &f%clan_name_9% &7- &#9AB128%value_9%"
    - "&#34AA0010. &f%clan_name_10% &7- &#9AB128%value_10%"
  # Топ 10 по килам
  clan-top-kills:
    - ""
    - "&#C50000Т&#C70000о&#C90000п &#CC0000к&#CE0000л&#D00000а&#D10000н&#D30000о&#D50000в &#D90000п&#DA0000о &#DE0000у&#E00000б&#E20000и&#E30000й&#E50000с&#E70000т&#E90000в&#EA0000а&#EC0000м&#EE0000:"
    - ""
    - "&#EE72001. &f%clan_name_1% &7- &#EE4800%value_1%"
    - "&#EE72002. &f%clan_name_2% &7- &#EE4800%value_2%"
    - "&#EE72003. &f%clan_name_3% &7- &#EE4800%value_3%"
    - "&#EE72004. &f%clan_name_4% &7- &#EE4800%value_4%"
    - "&#EE72005. &f%clan_name_5% &7- &#EE4800%value_5%"
    - "&#EE72006. &f%clan_name_6% &7- &#EE4800%value_6%"
    - "&#EE72007. &f%clan_name_7% &7- &#EE4800%value_7%"
    - "&#EE72008. &f%clan_name_8% &7- &#EE4800%value_8%"
    - "&#EE72009. &f%clan_name_9% &7- &#EE4800%value_9%"
    - "&#EE720010. &f%clan_name_10% &7- &#EE4800%value_10%"